### ISSUE TITLE
Strange wallet.history work

### ISSUE THREAD

**Issue by kesha1225** [uwinx/aioqiwi#18]
I got this object after call ```wallet.history()[0]```:
```
History(account='+79531658261', comment='123lat_comment', currency_rate=1, date='2020-03-12T22:24:19+03:00', error=None, error_code=0, payment_extras=[], person_id=79040585807, status='SUCCESS', status_text='Success', trm_txn_id='1583030256', txn_id=17927768283, type='IN')
```

Where is sum and commission?

**Comment by uwinx** [comment]
@kesha1225, can you try to use non-model return policy setting `wallet.as_model = False`

**Comment by uwinx** [comment]
@kesha1225, issue has been open for month. Could you solve your problem changing return policy?

**Comment by uwinx** [comment]
Closing. Irrelevant.
