### ISSUE TITLE
Switch to pydantic.

### ISSUE THREAD

**Issue by kesha1225** [uwinx/aioqiwi#19]
Why are you using strange models with with the equally strange converters, such as ```json_to_model```. What's this for?? Use [pydantic](https://pypi.org/project/pydantic/), please.

**Comment by uwinx** [comment]
@kesha1225, by that time I didn't consider that chance. If you look at dev1.x branch it's no more of
> _strange models with with the equally strange converters_

Thanks for support.

**Comment by kesha1225** [comment]
Ok, its good
